---

name: gcp.labbox-deploy

trigger: none

pool:
  vmImage: windows-2019

variables:
  - group: gcp.labrink72.vars
  - name: gcpKeyData
    value: $[variables.pipelineautomationkeyfile]

parameters:
  - name: apply
    displayName: Deploy infrastructure
    type: boolean
    default: false

resources:
  repositories:
    - repository: infrastructure
      type: github
      name: rink72/lab-infrastructure
      ref: refs/tags/0.3.0
      endpoint: rink72
    - repository: templates
      type: github
      name: rink72/lab-templates
      ref: refs/tags/0.1.0
      endpoint: rink72

stages:
  - stage: Deploy
    displayName: Infrastructure deploy
    jobs:
    - template: templates/jobs/infrastructure-deploy.yml@templates
      parameters:
        cloudType: GCP
        service: labbox
        gcpKeyData: $(gcpKeyData)
        apply: ${{ parameters.apply }}
