parameters:
  publish: false

jobs:
- job: Build
  workspace:
    clean: all
  variables:
  - template: variables.yml
  steps:
  - checkout: self
  - checkout: terragrunt
  - ${{ if parameters.publish }}:
    - publish: ${{ variables.infrastructureArtifactSourcePath }}
      artifact: ${{ variables.infrastructureArtifactName }}
      displayName: Publish infrastructure artifact
    - publish: ${{ variables.terragruntArtifactSourcePath }}
      artifact: ${{ variables.terragruntArtifactName }}
      displayName: Publish terragrunt artifact